// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vaccelerator_tb__Syms.h"


void Vaccelerator_tb___024root__trace_chg_0_sub_0(Vaccelerator_tb___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vaccelerator_tb___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vaccelerator_tb___024root__trace_chg_0\n"); );
    // Init
    Vaccelerator_tb___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vaccelerator_tb___024root*>(voidSelf);
    Vaccelerator_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vaccelerator_tb___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vaccelerator_tb___024root__trace_chg_0_sub_0(Vaccelerator_tb___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vaccelerator_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vaccelerator_tb___024root__trace_chg_0_sub_0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    if (VL_UNLIKELY((vlSelfRef.__Vm_traceActivity[1U] 
                     | vlSelfRef.__Vm_traceActivity
                     [2U]))) {
        bufp->chgBit(oldp+0,(vlSelfRef.accelerator_tb__DOT__rst));
        bufp->chgIData(oldp+1,(vlSelfRef.accelerator_tb__DOT__mem_K_tiles[0]),32);
        bufp->chgIData(oldp+2,(vlSelfRef.accelerator_tb__DOT__mem_K_tiles[1]),32);
        bufp->chgIData(oldp+3,(vlSelfRef.accelerator_tb__DOT__mem_K_tiles[2]),32);
        bufp->chgIData(oldp+4,(vlSelfRef.accelerator_tb__DOT__mem_K_tiles[3]),32);
        bufp->chgIData(oldp+5,(vlSelfRef.accelerator_tb__DOT__mem_K_tiles[4]),32);
        bufp->chgIData(oldp+6,(vlSelfRef.accelerator_tb__DOT__mem_K_tiles[5]),32);
        bufp->chgIData(oldp+7,(vlSelfRef.accelerator_tb__DOT__mem_K_tiles[6]),32);
        bufp->chgIData(oldp+8,(vlSelfRef.accelerator_tb__DOT__mem_K_tiles[7]),32);
        bufp->chgIData(oldp+9,(vlSelfRef.accelerator_tb__DOT__fd_out),32);
    }
    if (VL_UNLIKELY((vlSelfRef.__Vm_traceActivity[3U] 
                     | vlSelfRef.__Vm_traceActivity
                     [4U]))) {
        bufp->chgIData(oldp+10,(vlSelfRef.accelerator_tb__DOT__push_thread__DOT__tile_ptr),32);
        bufp->chgIData(oldp+11,(vlSelfRef.accelerator_tb__DOT__push_thread__DOT__unnamedblk1__DOT__t),32);
        bufp->chgIData(oldp+12,(vlSelfRef.accelerator_tb__DOT__push_thread__DOT__unnamedblk1__DOT__unnamedblk2__DOT__k_tiles),32);
        bufp->chgIData(oldp+13,(vlSelfRef.accelerator_tb__DOT__push_thread__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk3__DOT__k),32);
        bufp->chgIData(oldp+14,(vlSelfRef.accelerator_tb__DOT__push_thread__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk3__DOT__unnamedblk4__DOT__i),32);
        bufp->chgIData(oldp+15,(vlSelfRef.accelerator_tb__DOT__push_thread__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk3__DOT__unnamedblk5__DOT__i),32);
    }
    if (VL_UNLIKELY((vlSelfRef.__Vm_traceActivity[5U] 
                     | vlSelfRef.__Vm_traceActivity
                     [7U]))) {
        bufp->chgBit(oldp+16,(vlSelfRef.accelerator_tb__DOT__s_axis_tready));
        bufp->chgBit(oldp+17,(vlSelfRef.accelerator_tb__DOT__dut__DOT__load_done));
        bufp->chgBit(oldp+18,(vlSelfRef.accelerator_tb__DOT__dut__DOT__load_is_last));
        bufp->chgBit(oldp+19,(vlSelfRef.accelerator_tb__DOT__dut__DOT__wr_en_a));
        bufp->chgBit(oldp+20,(vlSelfRef.accelerator_tb__DOT__dut__DOT__wr_en_b));
        bufp->chgCData(oldp+21,(vlSelfRef.accelerator_tb__DOT__dut__DOT__axi_in_inst__DOT__next_state),2);
        bufp->chgCData(oldp+22,(vlSelfRef.accelerator_tb__DOT__dut__DOT__axi_in_inst__DOT__next_beat_cnt),4);
    }
    if (VL_UNLIKELY(vlSelfRef.__Vm_traceActivity[6U])) {
        bufp->chgWData(oldp+23,(vlSelfRef.accelerator_tb__DOT__dut__DOT__axi_out_inst__DOT__data_reg),256);
        bufp->chgBit(oldp+31,(vlSelfRef.accelerator_tb__DOT__dut__DOT__axi_out_inst__DOT__valid_reg));
        bufp->chgBit(oldp+32,(vlSelfRef.accelerator_tb__DOT__dut__DOT__axi_out_inst__DOT__last_reg));
        bufp->chgBit(oldp+33,(vlSelfRef.accelerator_tb__DOT__dut__DOT__load_ready));
        bufp->chgBit(oldp+34,(vlSelfRef.accelerator_tb__DOT__dut__DOT__compute_done));
        bufp->chgBit(oldp+35,(vlSelfRef.accelerator_tb__DOT__dut__DOT__compute_ready));
        bufp->chgBit(oldp+36,(vlSelfRef.accelerator_tb__DOT__dut__DOT__compute_is_last));
        bufp->chgBit(oldp+37,(vlSelfRef.accelerator_tb__DOT__dut__DOT__buf_ctrl_inst__DOT__compute_ptr));
        bufp->chgBit(oldp+38,(vlSelfRef.accelerator_tb__DOT__dut__DOT__buf_ctrl_inst__DOT__load_ptr));
        bufp->chgCData(oldp+39,((7U & (IData)(vlSelfRef.accelerator_tb__DOT__dut__DOT__axi_in_inst__DOT__beat_cnt))),3);
        bufp->chgBit(oldp+40,(vlSelfRef.accelerator_tb__DOT__dut__DOT__rd_en));
        bufp->chgCData(oldp+41,((7U & (IData)(vlSelfRef.accelerator_tb__DOT__dut__DOT__acc_ctrl_inst__DOT__t_cnt))),3);
        bufp->chgBit(oldp+42,(vlSelfRef.accelerator_tb__DOT__dut__DOT__rd_phase));
        bufp->chgBit(oldp+43,(vlSelfRef.accelerator_tb__DOT__dut__DOT__rd_phase_q));
        bufp->chgQData(oldp+44,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_a_inst.rd_data),64);
        bufp->chgQData(oldp+46,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_b_inst.rd_data),64);
        bufp->chgBit(oldp+48,(vlSelfRef.accelerator_tb__DOT__dut__DOT__array_en));
        bufp->chgBit(oldp+49,(vlSelfRef.accelerator_tb__DOT__dut__DOT__array_clear));
        bufp->chgBit(oldp+50,(vlSelfRef.accelerator_tb__DOT__dut__DOT__array_drain));
        bufp->chgQData(oldp+51,(vlSelfRef.accelerator_tb__DOT__dut__DOT__flat_a_in),64);
        bufp->chgQData(oldp+53,(vlSelfRef.accelerator_tb__DOT__dut__DOT__flat_b_in),64);
        bufp->chgWData(oldp+55,(vlSelfRef.accelerator_tb__DOT__dut__DOT__flat_acc_out),256);
        bufp->chgBit(oldp+63,(vlSelfRef.accelerator_tb__DOT__dut__DOT__internal_valid));
        bufp->chgBit(oldp+64,((1U & (~ (IData)(vlSelfRef.accelerator_tb__DOT__dut__DOT__axi_out_inst__DOT__skid_valid_reg)))));
        bufp->chgBit(oldp+65,(vlSelfRef.accelerator_tb__DOT__dut__DOT__internal_last));
        bufp->chgQData(oldp+66,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_a.skewed_data_out_flat),64);
        bufp->chgQData(oldp+68,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_b.skewed_data_out_flat),64);
        bufp->chgCData(oldp+70,(vlSelfRef.accelerator_tb__DOT__dut__DOT__acc_ctrl_inst__DOT__state),2);
        bufp->chgCData(oldp+71,(vlSelfRef.accelerator_tb__DOT__dut__DOT__acc_ctrl_inst__DOT__next_state),2);
        bufp->chgCData(oldp+72,(vlSelfRef.accelerator_tb__DOT__dut__DOT__acc_ctrl_inst__DOT__t_cnt),6);
        bufp->chgCData(oldp+73,(vlSelfRef.accelerator_tb__DOT__dut__DOT__acc_ctrl_inst__DOT__next_t_cnt),6);
        bufp->chgBit(oldp+74,(vlSelfRef.accelerator_tb__DOT__dut__DOT__acc_ctrl_inst__DOT__is_first_tile));
        bufp->chgBit(oldp+75,(vlSelfRef.accelerator_tb__DOT__dut__DOT__acc_ctrl_inst__DOT__next_is_first_tile));
        bufp->chgCData(oldp+76,(vlSelfRef.accelerator_tb__DOT__dut__DOT__axi_in_inst__DOT__state),2);
        bufp->chgCData(oldp+77,(vlSelfRef.accelerator_tb__DOT__dut__DOT__axi_in_inst__DOT__beat_cnt),4);
        bufp->chgWData(oldp+78,(vlSelfRef.accelerator_tb__DOT__dut__DOT__axi_out_inst__DOT__skid_data_reg),256);
        bufp->chgBit(oldp+86,(vlSelfRef.accelerator_tb__DOT__dut__DOT__axi_out_inst__DOT__skid_last_reg));
        bufp->chgBit(oldp+87,(vlSelfRef.accelerator_tb__DOT__dut__DOT__axi_out_inst__DOT__skid_valid_reg));
        bufp->chgBit(oldp+88,(vlSelfRef.accelerator_tb__DOT__dut__DOT__buf_ctrl_inst__DOT__bank0_valid));
        bufp->chgBit(oldp+89,(vlSelfRef.accelerator_tb__DOT__dut__DOT__buf_ctrl_inst__DOT__bank1_valid));
        bufp->chgBit(oldp+90,(vlSelfRef.accelerator_tb__DOT__dut__DOT__buf_ctrl_inst__DOT__bank0_is_last));
        bufp->chgBit(oldp+91,(vlSelfRef.accelerator_tb__DOT__dut__DOT__buf_ctrl_inst__DOT__bank1_is_last));
        bufp->chgQData(oldp+92,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_a_inst.__PVT__bank0[0]),64);
        bufp->chgQData(oldp+94,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_a_inst.__PVT__bank0[1]),64);
        bufp->chgQData(oldp+96,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_a_inst.__PVT__bank0[2]),64);
        bufp->chgQData(oldp+98,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_a_inst.__PVT__bank0[3]),64);
        bufp->chgQData(oldp+100,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_a_inst.__PVT__bank0[4]),64);
        bufp->chgQData(oldp+102,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_a_inst.__PVT__bank0[5]),64);
        bufp->chgQData(oldp+104,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_a_inst.__PVT__bank0[6]),64);
        bufp->chgQData(oldp+106,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_a_inst.__PVT__bank0[7]),64);
        bufp->chgQData(oldp+108,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_a_inst.__PVT__bank1[0]),64);
        bufp->chgQData(oldp+110,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_a_inst.__PVT__bank1[1]),64);
        bufp->chgQData(oldp+112,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_a_inst.__PVT__bank1[2]),64);
        bufp->chgQData(oldp+114,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_a_inst.__PVT__bank1[3]),64);
        bufp->chgQData(oldp+116,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_a_inst.__PVT__bank1[4]),64);
        bufp->chgQData(oldp+118,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_a_inst.__PVT__bank1[5]),64);
        bufp->chgQData(oldp+120,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_a_inst.__PVT__bank1[6]),64);
        bufp->chgQData(oldp+122,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_a_inst.__PVT__bank1[7]),64);
        bufp->chgQData(oldp+124,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_b_inst.__PVT__bank0[0]),64);
        bufp->chgQData(oldp+126,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_b_inst.__PVT__bank0[1]),64);
        bufp->chgQData(oldp+128,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_b_inst.__PVT__bank0[2]),64);
        bufp->chgQData(oldp+130,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_b_inst.__PVT__bank0[3]),64);
        bufp->chgQData(oldp+132,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_b_inst.__PVT__bank0[4]),64);
        bufp->chgQData(oldp+134,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_b_inst.__PVT__bank0[5]),64);
        bufp->chgQData(oldp+136,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_b_inst.__PVT__bank0[6]),64);
        bufp->chgQData(oldp+138,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_b_inst.__PVT__bank0[7]),64);
        bufp->chgQData(oldp+140,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_b_inst.__PVT__bank1[0]),64);
        bufp->chgQData(oldp+142,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_b_inst.__PVT__bank1[1]),64);
        bufp->chgQData(oldp+144,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_b_inst.__PVT__bank1[2]),64);
        bufp->chgQData(oldp+146,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_b_inst.__PVT__bank1[3]),64);
        bufp->chgQData(oldp+148,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_b_inst.__PVT__bank1[4]),64);
        bufp->chgQData(oldp+150,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_b_inst.__PVT__bank1[5]),64);
        bufp->chgQData(oldp+152,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_b_inst.__PVT__bank1[6]),64);
        bufp->chgQData(oldp+154,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__buf_b_inst.__PVT__bank1[7]),64);
        bufp->chgCData(oldp+156,((0xffU & (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_a.skewed_data_out_flat))),8);
        bufp->chgCData(oldp+157,((0xffU & (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_b.skewed_data_out_flat))),8);
        bufp->chgCData(oldp+158,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__0__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+159,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__0__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+160,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__0__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+161,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__0__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+162,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__0__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+163,((0xffU & (IData)((vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_b.skewed_data_out_flat 
                                                   >> 8U)))),8);
        bufp->chgCData(oldp+164,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__1__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+165,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__1__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+166,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__1__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+167,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__1__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+168,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__1__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+169,((0xffU & (IData)((vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_b.skewed_data_out_flat 
                                                   >> 0x10U)))),8);
        bufp->chgCData(oldp+170,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__2__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+171,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__2__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+172,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__2__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+173,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__2__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+174,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__2__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+175,((0xffU & (IData)((vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_b.skewed_data_out_flat 
                                                   >> 0x18U)))),8);
        bufp->chgCData(oldp+176,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__3__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+177,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__3__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+178,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__3__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+179,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__3__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+180,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__3__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+181,((0xffU & (IData)((vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_b.skewed_data_out_flat 
                                                   >> 0x20U)))),8);
        bufp->chgCData(oldp+182,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__4__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+183,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__4__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+184,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__4__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+185,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__4__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+186,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__4__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+187,((0xffU & (IData)((vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_b.skewed_data_out_flat 
                                                   >> 0x28U)))),8);
        bufp->chgCData(oldp+188,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__5__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+189,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__5__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+190,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__5__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+191,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__5__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+192,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__5__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+193,((0xffU & (IData)((vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_b.skewed_data_out_flat 
                                                   >> 0x30U)))),8);
        bufp->chgCData(oldp+194,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__6__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+195,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__6__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+196,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__6__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+197,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__6__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+198,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__6__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+199,((0xffU & (IData)((vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_b.skewed_data_out_flat 
                                                   >> 0x38U)))),8);
        bufp->chgCData(oldp+200,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__7__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+201,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__7__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+202,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__7__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+203,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__7__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+204,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__0__KET____DOT__col__BRA__7__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+205,((0xffU & (IData)((vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_a.skewed_data_out_flat 
                                                   >> 8U)))),8);
        bufp->chgCData(oldp+206,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__0__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+207,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__0__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+208,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__0__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+209,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__0__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+210,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__0__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+211,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__1__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+212,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__1__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+213,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__1__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+214,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__1__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+215,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__1__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+216,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__2__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+217,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__2__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+218,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__2__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+219,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__2__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+220,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__2__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+221,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__3__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+222,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__3__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+223,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__3__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+224,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__3__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+225,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__3__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+226,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__4__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+227,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__4__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+228,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__4__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+229,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__4__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+230,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__4__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+231,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__5__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+232,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__5__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+233,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__5__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+234,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__5__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+235,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__5__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+236,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__6__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+237,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__6__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+238,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__6__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+239,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__6__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+240,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__6__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+241,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__7__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+242,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__7__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+243,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__7__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+244,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__7__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+245,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__1__KET____DOT__col__BRA__7__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+246,((0xffU & (IData)((vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_a.skewed_data_out_flat 
                                                   >> 0x10U)))),8);
        bufp->chgCData(oldp+247,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__0__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+248,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__0__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+249,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__0__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+250,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__0__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+251,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__0__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+252,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__1__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+253,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__1__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+254,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__1__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+255,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__1__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+256,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__1__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+257,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__2__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+258,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__2__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+259,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__2__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+260,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__2__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+261,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__2__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+262,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__3__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+263,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__3__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+264,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__3__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+265,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__3__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+266,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__3__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+267,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__4__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+268,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__4__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+269,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__4__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+270,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__4__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+271,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__4__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+272,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__5__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+273,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__5__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+274,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__5__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+275,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__5__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+276,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__5__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+277,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__6__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+278,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__6__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+279,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__6__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+280,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__6__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+281,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__6__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+282,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__7__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+283,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__7__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+284,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__7__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+285,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__7__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+286,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__2__KET____DOT__col__BRA__7__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+287,((0xffU & (IData)((vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_a.skewed_data_out_flat 
                                                   >> 0x18U)))),8);
        bufp->chgCData(oldp+288,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__0__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+289,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__0__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+290,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__0__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+291,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__0__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+292,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__0__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+293,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__1__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+294,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__1__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+295,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__1__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+296,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__1__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+297,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__1__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+298,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__2__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+299,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__2__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+300,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__2__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+301,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__2__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+302,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__2__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+303,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__3__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+304,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__3__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+305,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__3__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+306,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__3__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+307,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__3__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+308,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__4__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+309,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__4__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+310,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__4__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+311,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__4__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+312,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__4__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+313,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__5__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+314,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__5__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+315,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__5__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+316,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__5__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+317,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__5__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+318,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__6__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+319,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__6__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+320,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__6__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+321,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__6__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+322,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__6__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+323,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__7__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+324,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__7__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+325,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__7__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+326,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__7__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+327,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__3__KET____DOT__col__BRA__7__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+328,((0xffU & (IData)((vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_a.skewed_data_out_flat 
                                                   >> 0x20U)))),8);
        bufp->chgCData(oldp+329,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__0__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+330,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__0__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+331,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__0__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+332,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__0__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+333,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__0__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+334,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__1__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+335,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__1__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+336,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__1__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+337,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__1__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+338,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__1__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+339,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__2__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+340,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__2__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+341,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__2__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+342,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__2__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+343,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__2__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+344,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__3__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+345,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__3__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+346,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__3__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+347,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__3__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+348,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__3__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+349,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__4__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+350,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__4__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+351,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__4__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+352,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__4__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+353,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__4__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+354,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__5__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+355,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__5__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+356,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__5__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+357,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__5__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+358,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__5__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+359,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__6__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+360,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__6__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+361,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__6__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+362,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__6__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+363,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__6__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+364,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__7__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+365,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__7__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+366,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__7__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+367,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__7__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+368,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__4__KET____DOT__col__BRA__7__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+369,((0xffU & (IData)((vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_a.skewed_data_out_flat 
                                                   >> 0x28U)))),8);
        bufp->chgCData(oldp+370,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__0__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+371,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__0__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+372,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__0__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+373,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__0__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+374,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__0__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+375,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__1__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+376,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__1__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+377,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__1__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+378,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__1__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+379,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__1__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+380,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__2__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+381,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__2__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+382,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__2__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+383,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__2__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+384,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__2__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+385,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__3__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+386,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__3__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+387,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__3__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+388,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__3__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+389,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__3__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+390,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__4__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+391,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__4__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+392,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__4__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+393,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__4__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+394,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__4__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+395,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__5__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+396,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__5__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+397,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__5__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+398,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__5__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+399,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__5__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+400,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__6__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+401,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__6__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+402,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__6__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+403,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__6__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+404,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__6__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+405,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__7__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+406,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__7__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+407,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__7__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+408,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__7__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+409,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__5__KET____DOT__col__BRA__7__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+410,((0xffU & (IData)((vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_a.skewed_data_out_flat 
                                                   >> 0x30U)))),8);
        bufp->chgCData(oldp+411,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__0__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+412,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__0__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+413,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__0__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+414,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__0__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+415,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__0__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+416,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__1__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+417,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__1__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+418,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__1__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+419,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__1__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+420,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__1__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+421,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__2__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+422,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__2__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+423,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__2__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+424,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__2__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+425,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__2__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+426,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__3__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+427,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__3__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+428,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__3__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+429,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__3__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+430,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__3__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+431,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__4__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+432,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__4__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+433,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__4__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+434,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__4__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+435,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__4__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+436,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__5__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+437,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__5__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+438,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__5__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+439,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__5__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+440,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__5__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+441,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__6__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+442,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__6__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+443,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__6__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+444,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__6__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+445,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__6__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+446,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__7__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+447,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__7__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+448,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__7__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+449,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__7__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+450,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__6__KET____DOT__col__BRA__7__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+451,((0xffU & (IData)((vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__feeder_a.skewed_data_out_flat 
                                                   >> 0x38U)))),8);
        bufp->chgCData(oldp+452,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__0__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+453,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__0__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+454,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__0__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+455,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__0__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+456,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__0__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+457,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__1__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+458,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__1__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+459,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__1__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+460,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__1__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+461,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__1__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+462,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__2__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+463,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__2__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+464,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__2__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+465,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__2__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+466,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__2__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+467,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__3__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+468,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__3__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+469,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__3__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+470,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__3__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+471,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__3__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+472,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__4__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+473,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__4__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+474,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__4__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+475,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__4__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+476,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__4__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+477,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__5__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+478,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__5__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+479,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__5__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+480,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__5__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+481,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__5__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+482,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__6__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+483,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__6__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+484,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__6__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+485,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__6__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+486,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__6__KET____DOT__pe_inst.__PVT__product))),32);
        bufp->chgCData(oldp+487,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__7__KET____DOT__pe_inst.a_out),8);
        bufp->chgCData(oldp+488,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__7__KET____DOT__pe_inst.b_out),8);
        bufp->chgIData(oldp+489,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__7__KET____DOT__pe_inst.acc_out),32);
        bufp->chgSData(oldp+490,(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__7__KET____DOT__pe_inst.__PVT__product),16);
        bufp->chgIData(oldp+491,(VL_EXTENDS_II(32,16, (IData)(vlSymsp->TOP__accelerator_tb__DOT__dut__DOT__array_inst__DOT__row__BRA__7__KET____DOT__col__BRA__7__KET____DOT__pe_inst.__PVT__product))),32);
    }
    bufp->chgBit(oldp+492,(vlSelfRef.accelerator_tb__DOT__clk));
    bufp->chgQData(oldp+493,(vlSelfRef.accelerator_tb__DOT__s_axis_tdata),64);
    bufp->chgBit(oldp+495,(vlSelfRef.accelerator_tb__DOT__s_axis_tvalid));
    bufp->chgBit(oldp+496,(vlSelfRef.accelerator_tb__DOT__s_axis_tlast));
    bufp->chgBit(oldp+497,(vlSelfRef.accelerator_tb__DOT__m_axis_tready));
    bufp->chgIData(oldp+498,(vlSelfRef.accelerator_tb__DOT__pull_thread__DOT__unnamedblk6__DOT__t),32);
    bufp->chgIData(oldp+499,(vlSelfRef.accelerator_tb__DOT__pull_thread__DOT__unnamedblk6__DOT__unnamedblk7__DOT__i),32);
}

void Vaccelerator_tb___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vaccelerator_tb___024root__trace_cleanup\n"); );
    // Init
    Vaccelerator_tb___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vaccelerator_tb___024root*>(voidSelf);
    Vaccelerator_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    vlSymsp->__Vm_activity = false;
    vlSymsp->TOP.__Vm_traceActivity[0U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[1U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[2U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[3U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[4U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[5U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[6U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[7U] = 0U;
}
